"""empty message

Revision ID: 6f9511ed3480
Revises: ac94adeee8c4
Create Date: 2026-05-01 08:06:03.535446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9511ed3480'
down_revision = 'ac94adeee8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_date', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_product', schema=None) as batch_op:
        batch_op.drop_column('delivered')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('delivered_date')

    # ### end Alembic commands ###
